### ISSUE TITLE
out padding in Lab3-3 Decoder

### ISSUE THREAD

**Issue by mryzlee** [2017-fall-DL-training-program/VAE-GAN-and-VAE-GAN#12]
Do we still need out padding in Decoder of Lab3-3?
In 11/26 revision of Lab_VAE_GAN.pdf, there are newly added out padding configuration.
But in 11/27 revision of Lab_VAE_GAN.pdf, those are removed again.
Which one should we use?

**Comment by hui-po-wang** [comment]
Hi @mryzlee ,

That's a wrong version, just ignore it. Please use the latest one.
If you follow the usage below, you don't have to add output padding.

![image](https://user-images.githubusercontent.com/10228478/33311322-6cc11e3c-d45f-11e7-8a2b-0e093b82b9e7.png)

Thanks
