### ISSUE TITLE
Print result get truncated. 

### ISSUE THREAD

**Issue by mtkmark** [2017-fall-DL-training-program/VAE-GAN-and-VAE-GAN#13]
While printing out a large dimension tensor ( 100X10) , the result seems to be truncted.
Anyone knows how to print without benign truncated ? 
Thanks

==============================
Final Picture Variable containing:
-2.0000 -0.2478 -1.0780  ...   2.6202  0.5657 -0.2862
-1.5556 -0.2478 -1.0780  ...   2.6202  0.5657 -0.2862
-1.1111 -0.2478 -1.0780  ...   2.6202  0.5657 -0.2862
          ...             ⋱             ...
 2.4540 -0.2478 -1.0780  ...   2.6202  0.5657  1.1111
 2.4540 -0.2478 -1.0780  ...   2.6202  0.5657  1.5556
 2.4540 -0.2478 -1.0780  ...   2.6202  0.5657  2.0000
[torch.FloatTensor of size 100x10]

**Comment by hui-po-wang** [comment]
Hi @mtkmark ,

It's a default setting in numpy.
Please refer to https://stackoverflow.com/questions/1987694/how-to-print-the-full-numpy-array.

Thanks

**Comment by mtkmark** [comment]
Add the following in main.py  , doesn't seem to work, any more hint ? 
====
import numpy as np
np.set_printoptions(threshold=np.inf)
......
print ('Final Picture',sample)
====
Still get 
-2.0000 -0.2478 -1.0780  ...   2.6202  0.5657 -0.2862
-1.5556 -0.2478 -1.0780  ...   2.6202  0.5657 -0.2862
-1.1111 -0.2478 -1.0780  ...   2.6202  0.5657 -0.2862
          ...             ⋱             ...
 2.4540 -0.2478 -1.0780  ...   2.6202  0.5657  1.1111
 2.4540 -0.2478 -1.0780  ...   2.6202  0.5657  1.5556
 2.4540 -0.2478 -1.0780  ...   2.6202  0.5657  2.0000

**Comment by hui-po-wang** [comment]
maybe try this one ```torch.set_printoptions```

**Comment by mtkmark** [comment]
It works perfectly . Thanks  
=============
torch.set_printoptions(threshold=np.inf) 
=============
