### ISSUE TITLE
Beta VAE : Beta Value Setting 

### ISSUE THREAD

**Issue by mtkmark** [2017-fall-DL-training-program/VAE-GAN-and-VAE-GAN#15]
In the sample code 
  ===>  KLD = -0.5 * torch.sum .....    
It seems "0.5"  comes from original KL divergence. 

To increase KL divergence  by Beta value: 10 (for example) , should we do the following   ?
==> KLD =   10* -0.5  *torch.sum .....

**Comment by hui-po-wang** [comment]
Hi @mtkmark ,

Yes.

**Comment by mtkmark** [comment]
Thanks !
