### ISSUE TITLE
Feature-wise distance metrics in VAE-GAN

### ISSUE THREAD

**Issue by jessejchuang** [2017-fall-DL-training-program/VAE-GAN-and-VAE-GAN#18]
Hi TA,

In the TF code below, it seems the author uses **_gamma=1e-6_** but we use **_gamma=5_**. His metrics is put below as well. I'm wondering if your **L2 norm definition in the handout** is same as his or just use MSE without multiply with 1/2 and constant item. Could you share the formula? Thanks.

https://github.com/zhangqianhui/vae-gan-tensorflow/blob/master/vaegan.py#L84
Feature-wise distance metrics in TF = **_-(1/2)*log(2*pi) - (1/2)MSE(pred,target)_**

**Comment by hui-po-wang** [comment]
Hi @jessejchuang ,

I just used pure MSE as the metrics of feature matching without multiplying 1/2 or adding any constants.

However, you can use it if you think it's easier to implement hw.

Thanks
