### ISSUE TITLE
Download Data Fail

### ISSUE THREAD

**Issue by mtkmark** [2017-fall-DL-training-program/VAE-GAN-and-VAE-GAN#2]
A startup question.

While executing VAE.py , it tries to download the following file and encounter time out issues. 
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz

1.  I can download this file manually, but how can I place it into right location such that  main.py can go normally  ?    ../data/processed ? or raw ? 

Thanks

**Comment by hui-po-wang** [comment]
Hi @mtkmark ,

We've downloaded the dataset and put it into the dataset directory on Azure (should be the same one where CIFAR-10 locates).

The usage is the same as we used in LAB1 (CIFAR-10).

Thanks
