### ISSUE TITLE
Creating custom *.h5

### ISSUE THREAD

**Issue by yyrkoon27** [2017-fall-DL-training-program/VAE-GAN-and-VAE-GAN#26]
Dear TA,

I wonder if it is possible for you to share how to create a custom *.h5 (like CelebA_aligned_reduced.h5). This will be very helpful for our final projects and/or future works.

Thank you very much!

**Comment by hui-po-wang** [comment]
Hi @yyrkoon27 ,

Sorry, the alignment is not conducted by me, but I guess that OpenCV can achieve similar works.

As for h5py files, there are a lot of tutorials online. It's just a kind of storage format, you can use any data format in your customized class.

Thanks

**Comment by yyrkoon27** [comment]
Dear TA,

OK I got it. Thank you very much!
