### ISSUE TITLE
Latent Code Size = 10 , 

### ISSUE THREAD

**Issue by mtkmark** [2017-fall-DL-training-program/VAE-GAN-and-VAE-GAN#3]
To make Latent Code Size = 10 , Should we reduce Encoder Shape to 400,10 instead of 400,20 ? 
Thanks

      self.fc1 = nn.Linear(784, 400)
        self.fc21 = nn.Linear(400, 10)
        self.fc22 = nn.Linear(400, 10)
        self.fc3 = nn.Linear(10, 400)
        self.fc4 = nn.Linear(400, 784)

**Comment by hui-po-wang** [comment]
Hi @mtkmark,

Thank you for pointing out the error, and, yes, you are correct.

Sorry for my mistake. 
I just noticed the error in this morning and I've uploaded a new version on Github. 
I hope that HR has reminded you guys that the newest one is on Github.

Thanks
