### ISSUE TITLE
Generator cost function in Lab-3-2

### ISSUE THREAD

**Issue by Peter-Chuang** [2017-fall-DL-training-program/VAE-GAN-and-VAE-GAN#5]
Dear TA,

You said, there are two most often used loss function of generator. 
The first one is:
ℒG= −ℒ𝐷=Ex~pg[log(1−𝐷(𝑥))]
The second one is: 
ℒG= 𝐸𝑥~𝑝𝑔[log−𝐷(𝑥)]

For the second one, is that "𝐸𝑥~𝑝𝑔[log−𝐷(𝑥)]" or "-𝐸𝑥~𝑝𝑔[log𝐷(𝑥)]"?

Peter

**Comment by Peter-Chuang** [comment]
Something wrong when displaying the equation. I type them again.

The first one is:
ℒG= −ℒ𝐷=Expg[log(1 - 𝐷(𝑥))]
The second one is:
ℒG= 𝐸𝑥𝑝𝑔[log - 𝐷(𝑥)]

For the second one, is that "𝐸𝑥𝑝𝑔[log - 𝐷(𝑥)]" or " - 𝐸𝑥𝑝𝑔[log𝐷(𝑥)]"?

**Comment by hui-po-wang** [comment]
Oh, you are right.
It should be E [ -logD(x)]. 
Sorry for my mistake.

I'll update it as soon as possible, and thank you for pointing out the mistake.

Thanks

**Comment by Peter-Chuang** [comment]
Thanks!!
