### ISSUE TITLE
What should we use CelebA_aligned.h5 or CeleA_aligned_reduced.h5 ?

### ISSUE THREAD

**Issue by doom8199** [2017-fall-DL-training-program/VAE-GAN-and-VAE-GAN#6]
Dear TA:
    As title, I found that IT provide two different data-sets with prefix name "CeleA_aligned".
    I try to access google link outside MTK, and get CelebA_aligned.h5.
   Don't we care about CeleA_aligned_reduced.h5 ?

**Comment by hui-po-wang** [comment]
Hi @doom8199 ,

Please use "CelebA_aligned_reduced.h5". 

The google link in the pdf file is the "whole" dataset. To reduce the training time (the computation power of your machine is not as good as I expected), I provide a reduced version and I have removed the link in the pdf file to avoid confusion.

By the way, no matter which one you use, you will get similar results. The only difference is the training time.

Thanks

**Comment by doom8199** [comment]
Thanks !

**Comment by ytkuo412** [comment]
Dear TA,

I only see CelebA_aligned.h5 but not CelebA_aligned_reduced.h5 in following path /homework/dataset.

Where can I get CelebA_aligned_reduced.h5?

BTW, when I train DCGAN with CelebA_aligned.h5, I find that the discriminator will become too strong. That is D(x) ~ 1 and D(G(x0)) ~ 0. Shouldn't I use Celeba_aligned.h5?

Thanks.
