### ISSUE TITLE
[Lab 3-1] log variance to std

### ISSUE THREAD

**Issue by fansia** [2017-fall-DL-training-program/VAE-GAN-and-VAE-GAN#9]
Hi TA:

I don't understand why:  ( log(variance) / 2 ).exp_()  = std.
Could you give me some link to study?
Thank you.

**Comment by hui-po-wang** [comment]
Hi @fansia ,

Let's begin with some basic properties:
1. log(a^(1/2)) = 1/2 * log (a)
2. standard deviation = sqrt(variance)
3. exp(log(a)) = log(exp(a)) = a

To prove  ( log(variance) / 2 ).exp_() = std, we can first rewrite the original function into this form according to (1):
log(variance^(1/2)).exp()
By (2), we can get:
log (std).exp()
Then, by (3), we can get:
log (std).exp() = std

Thanks

**Comment by fansia** [comment]
got it. thank you very much. :)
